# -*- coding: utf-8 -*-
"""To_do_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15izQyOlLj88aiwtMk7UZJJohXqThBGKB
"""

tasks = []

def show_menu():
    print("\n--- To-Do List Menu ---")
    print("1. View Tasks")
    print("2. Add Task")
    print("3. Mark Task as Completed")
    print("4. Delete Task")
    print("5. Exit")

def view_tasks():
    if not tasks:
        print("\nNo tasks found.")
    else:
        print("\nYour Tasks:")
        for i, (task, completed) in enumerate(tasks, start=1):
            status = "✔ Done" if completed else "Pending"
            print(f"{i}. {task} [{status}]")

def add_task():
    task = input("Enter the new task: ").strip()
    if task:
        tasks.append([task, False])
        print(" Task added successfully!")

def mark_task_completed():
    view_tasks()
    try:
        choice = int(input("Enter task number to mark as completed: "))
        if 1 <= choice <= len(tasks):
            tasks[choice - 1][1] = True
            print("Task marked as completed!")
        else:
            print(" Invalid task number.")
    except ValueError:
        print(" Please enter a valid number.")

def delete_task():
    view_tasks()
    try:
        choice = int(input("Enter task number to delete: "))
        if 1 <= choice <= len(tasks):
            removed = tasks.pop(choice - 1)
            print(f"🗑 Task '{removed[0]}' deleted!")
        else:
            print("Invalid task number.")
    except ValueError:
        print("Please enter a valid number.")

while True:
    show_menu()
    option = input("Choose an option (1-5): ").strip()

    if option == "1":
        view_tasks()
    elif option == "2":
        add_task()
    elif option == "3":
        mark_task_completed()
    elif option == "4":
        delete_task()
    elif option == "5":
        print("Exiting To-Do List. Goodbye!")
        break
    else:
        print(" Invalid option. Please try again.")